-- Self-checking read-feature suite for the Firebird catalog extension.
--
-- Run via native/test_queries.sh, which prepends the ATTACH statement. Each
-- check emits a single `name|PASS|FAIL` row; the runner fails if any row is FAIL.
-- Expected values are derived from test/initdb/01_schema.sql.

-- A native (non-Firebird) table, used to prove cross-database joins.
CREATE TEMP TABLE bonus (emp_id INTEGER, amount INTEGER);
INSERT INTO bonus VALUES (1, 5000), (2, 7000), (3, 1000);

.mode list
.headers off
.nullvalue NULL

-- ---- catalog / metadata ----
SELECT 'catalog_table_count', CASE WHEN (SELECT count(*) FROM (SHOW ALL TABLES) WHERE database='fb')=4 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'information_schema', CASE WHEN (SELECT count(*) FROM information_schema.columns WHERE table_catalog='fb' AND table_name='EMPLOYEES')=8 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'describe_columns', CASE WHEN (SELECT count(*) FROM (DESCRIBE fb.PROJECTS))=5 THEN 'PASS' ELSE 'FAIL' END;

-- ---- basic scans / projection / filter ----
SELECT 'count_employees', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES)=4 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'projection_single_col', CASE WHEN (SELECT count(DISTINCT FIRST_NAME) FROM fb.EMPLOYEES)=4 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'where_boolean', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES WHERE ACTIVE)=2 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'where_null', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES WHERE SALARY IS NULL)=1 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'where_compare', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES WHERE SALARY > 96000)=2 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'like_filter', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES WHERE LAST_NAME LIKE '%o%')=3 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'in_list', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES WHERE DEPT_ID IN (1,2))=3 THEN 'PASS' ELSE 'FAIL' END;
-- pushdown edge cases (translated into the Firebird WHERE; must preserve SQL 3-valued logic)
SELECT 'where_or', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES WHERE SALARY > 100000 OR DEPT_ID = 1)=3 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'where_not_equal', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES WHERE DEPT_ID <> 1)=1 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'where_between', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES WHERE SALARY BETWEEN 95000 AND 100000)=2 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'where_string_eq', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES WHERE FIRST_NAME = 'Ada')=1 THEN 'PASS' ELSE 'FAIL' END;

-- ---- ordering / limit / offset / distinct ----
SELECT 'order_limit', CASE WHEN (SELECT FIRST_NAME FROM fb.EMPLOYEES ORDER BY SALARY DESC NULLS LAST LIMIT 1)='Alan' THEN 'PASS' ELSE 'FAIL' END;
SELECT 'order_offset', CASE WHEN (SELECT FIRST_NAME FROM fb.EMPLOYEES ORDER BY ID LIMIT 1 OFFSET 2)='Grace' THEN 'PASS' ELSE 'FAIL' END;
SELECT 'distinct', CASE WHEN (SELECT count(*) FROM (SELECT DISTINCT DEPT_ID FROM fb.EMPLOYEES))=3 THEN 'PASS' ELSE 'FAIL' END;
-- limit pushdown (pushed into Firebird as a ROWS clause; DuckDB still enforces LIMIT/OFFSET)
SELECT 'limit_pushdown', CASE WHEN (SELECT count(*) FROM (SELECT FIRST_NAME FROM fb.EMPLOYEES LIMIT 2))=2 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'limit_offset_pushdown', CASE WHEN (SELECT count(*) FROM (SELECT FIRST_NAME FROM fb.EMPLOYEES LIMIT 2 OFFSET 1))=2 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'limit_over_rowcount', CASE WHEN (SELECT count(*) FROM (SELECT FIRST_NAME FROM fb.EMPLOYEES LIMIT 100))=4 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'limit_with_filter', CASE WHEN (SELECT count(*) FROM (SELECT FIRST_NAME FROM fb.EMPLOYEES WHERE DEPT_ID=1 LIMIT 1))=1 THEN 'PASS' ELSE 'FAIL' END;

-- ---- aggregation ----
SELECT 'agg_sum', CASE WHEN abs((SELECT sum(SALARY) FROM fb.EMPLOYEES) - 299000.75) < 0.01 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'agg_minmax', CASE WHEN (SELECT max(SALARY) FROM fb.EMPLOYEES) > 105000 AND (SELECT min(SALARY) FROM fb.EMPLOYEES) < 95001 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'group_by', CASE WHEN abs((SELECT sum(SALARY) FROM fb.EMPLOYEES WHERE DEPT_ID=1) - 194000.25) < 0.01 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'having', CASE WHEN (SELECT count(*) FROM (SELECT DEPT_ID FROM fb.EMPLOYEES GROUP BY DEPT_ID HAVING count(*)>1))=1 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'agg_filter', CASE WHEN (SELECT count(*) FILTER (WHERE ACTIVE) FROM fb.EMPLOYEES)=2 THEN 'PASS' ELSE 'FAIL' END;

-- ---- joins ----
SELECT 'inner_join', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES e JOIN fb.DEPARTMENTS d ON e.DEPT_ID=d.ID)=3 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'left_join', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES e LEFT JOIN fb.DEPARTMENTS d ON e.DEPT_ID=d.ID)=4 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'left_join_null', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES e LEFT JOIN fb.DEPARTMENTS d ON e.DEPT_ID=d.ID WHERE d.ID IS NULL)=1 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'right_join', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES e RIGHT JOIN fb.DEPARTMENTS d ON e.DEPT_ID=d.ID WHERE e.ID IS NULL)=1 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'full_outer_join', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES e FULL OUTER JOIN fb.DEPARTMENTS d ON e.DEPT_ID=d.ID)=5 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'cross_join', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES CROSS JOIN fb.DEPARTMENTS)=12 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'three_table_join', CASE WHEN (SELECT count(*) FROM fb.PROJECTS p JOIN fb.DEPARTMENTS d ON p.DEPT_ID=d.ID JOIN fb.EMPLOYEES e ON p.LEAD_ID=e.ID)=4 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'self_join', CASE WHEN (SELECT m.FIRST_NAME FROM fb.EMPLOYEES e JOIN fb.DEPARTMENTS d ON e.DEPT_ID=d.ID JOIN fb.EMPLOYEES m ON d.MANAGER_ID=m.ID WHERE e.ID=3)='Ada' THEN 'PASS' ELSE 'FAIL' END;
SELECT 'using_join', CASE WHEN (SELECT count(*) FROM fb.PROJECTS JOIN fb.DEPARTMENTS USING (DEPT_ID))=4 THEN 'PASS' ELSE 'FAIL' END;

-- ---- subqueries ----
SELECT 'subquery_in', CASE WHEN (SELECT count(*) FROM fb.DEPARTMENTS WHERE ID IN (SELECT DEPT_ID FROM fb.PROJECTS WHERE HOURS>1000))=1 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'correlated_subquery', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES e WHERE e.SALARY > (SELECT avg(e2.SALARY) FROM fb.EMPLOYEES e2 WHERE e2.DEPT_ID=e.DEPT_ID))=1 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'exists', CASE WHEN (SELECT count(*) FROM fb.DEPARTMENTS d WHERE EXISTS (SELECT 1 FROM fb.PROJECTS p WHERE p.DEPT_ID=d.ID))=3 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'scalar_subquery', CASE WHEN (SELECT (SELECT count(*) FROM fb.PROJECTS))=4 THEN 'PASS' ELSE 'FAIL' END;

-- ---- CTEs and window functions ----
SELECT 'cte', CASE WHEN abs((WITH dc AS (SELECT DEPT_ID, sum(SALARY) total FROM fb.EMPLOYEES GROUP BY DEPT_ID) SELECT total FROM dc WHERE DEPT_ID=1) - 194000.25) < 0.01 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'window_rank', CASE WHEN (SELECT r FROM (SELECT ID, rank() OVER (PARTITION BY DEPT_ID ORDER BY SALARY DESC) r FROM fb.EMPLOYEES WHERE DEPT_ID=1) WHERE ID=3)=1 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'window_sum', CASE WHEN (SELECT count(DISTINCT s) FROM (SELECT sum(SALARY) OVER () s FROM fb.EMPLOYEES))=1 THEN 'PASS' ELSE 'FAIL' END;

-- ---- set operations ----
SELECT 'union_all', CASE WHEN (SELECT count(*) FROM (SELECT NAME FROM fb.DEPARTMENTS UNION ALL SELECT FIRST_NAME FROM fb.EMPLOYEES))=7 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'union_distinct', CASE WHEN (SELECT count(*) FROM (SELECT DEPT_ID FROM fb.EMPLOYEES UNION SELECT ID FROM fb.DEPARTMENTS))=4 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'intersect', CASE WHEN (SELECT count(*) FROM (SELECT DEPT_ID FROM fb.EMPLOYEES INTERSECT SELECT ID FROM fb.DEPARTMENTS))=2 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'except', CASE WHEN (SELECT count(*) FROM (SELECT ID FROM fb.DEPARTMENTS EXCEPT SELECT DEPT_ID FROM fb.EMPLOYEES))=1 THEN 'PASS' ELSE 'FAIL' END;

-- ---- expressions / scalar functions ----
SELECT 'case_expr', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES WHERE CASE WHEN SALARY>100000 THEN 1 ELSE 0 END = 1)=1 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'string_fn', CASE WHEN (SELECT upper(FIRST_NAME) FROM fb.EMPLOYEES WHERE ID=1)='ADA' THEN 'PASS' ELSE 'FAIL' END;
SELECT 'coalesce', CASE WHEN (SELECT coalesce(DEPARTMENT,'none') FROM fb.EMPLOYEES WHERE ID=4)='none' THEN 'PASS' ELSE 'FAIL' END;
SELECT 'date_fn', CASE WHEN (SELECT year(HIRED_ON) FROM fb.EMPLOYEES WHERE ID=1)=2019 THEN 'PASS' ELSE 'FAIL' END;

-- ---- cross-database join (Firebird table x native DuckDB temp table) ----
SELECT 'cross_db_join', CASE WHEN (SELECT count(*) FROM fb.EMPLOYEES e JOIN bonus b ON e.ID=b.emp_id)=3 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'cross_db_sum', CASE WHEN (SELECT sum(b.amount) FROM fb.EMPLOYEES e JOIN bonus b ON e.ID=b.emp_id WHERE e.ACTIVE)=12000 THEN 'PASS' ELSE 'FAIL' END;

-- ---- type fidelity (TYPE_GALLERY) ----
SELECT 'type_bigint', CASE WHEN (SELECT C_BIGINT FROM fb.TYPE_GALLERY WHERE ID=1)=9000000000000 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'type_smallint', CASE WHEN (SELECT C_SMALLINT FROM fb.TYPE_GALLERY WHERE ID=1)=32000 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'type_boolean', CASE WHEN (SELECT C_BOOLEAN FROM fb.TYPE_GALLERY WHERE ID=1)=TRUE THEN 'PASS' ELSE 'FAIL' END;
SELECT 'type_date', CASE WHEN (SELECT C_DATE FROM fb.TYPE_GALLERY WHERE ID=1)=DATE '2021-06-15' THEN 'PASS' ELSE 'FAIL' END;
SELECT 'type_time', CASE WHEN (SELECT C_TIME FROM fb.TYPE_GALLERY WHERE ID=1)=TIME '13:45:30' THEN 'PASS' ELSE 'FAIL' END;
SELECT 'type_timestamp', CASE WHEN (SELECT year(C_TIMESTAMP) FROM fb.TYPE_GALLERY WHERE ID=1)=2021 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'type_numeric', CASE WHEN abs((SELECT C_NUMERIC FROM fb.TYPE_GALLERY WHERE ID=1) - 12345.6789) < 0.001 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'type_double', CASE WHEN abs((SELECT C_DOUBLE FROM fb.TYPE_GALLERY WHERE ID=1) - 2.718281828) < 0.0001 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'type_blob_text', CASE WHEN (SELECT length(C_BLOB_TEXT) FROM fb.TYPE_GALLERY WHERE ID=1) > 10 THEN 'PASS' ELSE 'FAIL' END;
SELECT 'type_varchar', CASE WHEN (SELECT C_VARCHAR FROM fb.TYPE_GALLERY WHERE ID=1)='a varchar value' THEN 'PASS' ELSE 'FAIL' END;
SELECT 'type_all_null_row', CASE WHEN (SELECT count(*) FROM fb.TYPE_GALLERY WHERE ID=2 AND C_SMALLINT IS NULL AND C_BLOB_TEXT IS NULL AND C_TIMESTAMP IS NULL)=1 THEN 'PASS' ELSE 'FAIL' END;
